"""create impact_stats table

Revision ID: 6ce563749337
Revises: 
Create Date: 2025-07-04 16:47:52.627523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ce563749337'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('impact_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('helped_people', sa.Integer(), nullable=False),
    sa.Column('disasters_assisted', sa.Integer(), nullable=False),
    sa.Column('partners_onboarded', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_impact_stats_id'), 'impact_stats', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_impact_stats_id'), table_name='impact_stats')
    op.drop_table('impact_stats')
    # ### end Alembic commands ###
